// <auto-generated />
using System;
using BookStoreMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookStoreMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250616071755_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("BookStoreMVC.Models.Author", b =>
                {
                    b.Property<int>("AuthorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorID");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorID = 1,
                            Bio = "Penulis Novel Inspiratif",
                            Name = "Andrea Hirata"
                        },
                        new
                        {
                            AuthorID = 2,
                            Bio = "Penulis Novel Fiksi",
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            AuthorID = 3,
                            Bio = "Penulis Novel Sejarah",
                            Name = "Pramoedya Ananta Toer"
                        },
                        new
                        {
                            AuthorID = 4,
                            Bio = "Penulis Novel Fantasi",
                            Name = "J.R.R. Tolkien"
                        },
                        new
                        {
                            AuthorID = 5,
                            Bio = "Penulis Novel Fantasi",
                            Name = "J.R.R. Tolkien"
                        });
                });

            modelBuilder.Entity("BookStoreMVC.Models.Book", b =>
                {
                    b.Property<int>("BookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(8,2)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("BookID");

                    b.HasIndex("AuthorID");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookID = 1,
                            AuthorID = 1,
                            Price = 10.91m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(2001),
                            Title = "Laskar Pelangi"
                        },
                        new
                        {
                            BookID = 2,
                            AuthorID = 2,
                            Price = 30.45m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1965),
                            Title = "Harry Potter and The Philosopher's Stone"
                        },
                        new
                        {
                            BookID = 3,
                            AuthorID = 3,
                            Price = 25.10m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1955),
                            Title = "Bumi Manusia"
                        },
                        new
                        {
                            BookID = 4,
                            AuthorID = 4,
                            Price = 50.67m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1918),
                            Title = "The Lord Of The Ring The Fellowship Of The Ring"
                        },
                        new
                        {
                            BookID = 5,
                            AuthorID = 5,
                            Price = 40.43m,
                            ReleaseDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified).AddTicks(1993),
                            Title = "The Lord Of The Ring The Two Towers"
                        });
                });

            modelBuilder.Entity("BookStoreMVC.Models.Book", b =>
                {
                    b.HasOne("BookStoreMVC.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookStoreMVC.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
